export default {
    content: ['./index.html', './src/**/*.{ts,tsx}'],
    theme: {
        extend: {
            colors: {
                canvas: '#09111F',
                surface1: '#0F1727',
                surface2: '#172236',
                'phase-hook': '#FF8F66',
                'phase-foundation': '#7CA8FF',
                'phase-mechanism': '#73D2B4',
                'phase-evidence': '#B49CFF',
                'phase-implications': '#F3B773',
                'phase-synthesis': '#FFD089',
                'phase-comparison': '#F59E7A',
                'phase-query': '#73D2B4',
                'phase-amber': '#F3B773',
                'phase-blue': '#7CA8FF',
                'phase-teal': '#73D2B4',
                'phase-violet': '#B49CFF',
                'phase-rose': '#FF8F66',
                'phase-orange': '#F59E7A',
                'phase-green': '#73D2B4',
                'accent-clay': '#FF8F66',
                'accent-blue': '#7CA8FF',
                'accent-matcha': '#73D2B4',
                text1: '#F7F3EB',
                text2: '#C9D2E3',
                text3: '#7F90AC',
            },
            boxShadow: {
                glass: '0 28px 70px rgba(0, 0, 0, 0.3)',
            },
            fontFamily: {
                display: ['Fraunces', 'Georgia', 'serif'],
                body: ['Manrope', 'system-ui', 'sans-serif'],
                mono: ['IBM Plex Mono', 'monospace'],
            },
        },
    },
    plugins: [],
};
